### ISSUE TITLE
Many false positives in the `languages.register*` family

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/vscode-theia-comparator#30]
When checking for example `registerCallHierarchyProvider`, the `details` of the parsed VSCode version list the type of both parameters and the return as `any`. When parsing `theia.d.ts`, the fields are correctly populated.

First hit at breakpoint, parsing VSCode@main  
<img width="454" alt="image" src="https://user-images.githubusercontent.com/62660806/178852580-40de24b0-1c27-4d9d-91a6-69d99204f2f4.png">

Second hit, parsing Theia@master  
<img width="462" alt="image" src="https://user-images.githubusercontent.com/62660806/178852636-02c2b820-506b-4e16-8324-4aea262cd17f.png">

**Comment by JonasHelming** [comment]
@colin-grant-work Thank you for the report. I was already suspicious about this group. Are you working on a fix or shall we have a look?

**Comment by colin-grant-work** [comment]
I have not had a look yet - I haven't examined the parser or comparator very closely - so if you have the bandwidth, I'd appreciate your taking look.

**Comment by colin-grant-work** [comment]
@JonasHelming, it looks like it's probably a matter of an outdated TS version unable to handle some syntax somewhere and bailing out instead. I have updated TS (and graphql and graphql-request), and it looks like it does the trick for many of these declarations where older TS was getting confused. I'll push that update presently.
